{% set name = "riboSeed" %}
{% set version = "0.4.20" %}
{% set hash_type = "sha256" %}
{% set hash_value = "074879368f873b306e58f6a38f409498accf33decfa301b3ea7706b715b2816c" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://test-files.pythonhosted.org/packages/f4/96/3bbe71d6c69448f9b3adb8085dcbc946355b4ba1fdf21229af45a0cb202f/riboSeed-0.4.20.tar.gz
  # '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [win]
  skip: True  # [py2k]
  skip: True  # [py34]
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
requirements:
  build:
    - python
    - setuptools
    - biopython ==1.68
    - pysam ==0.11.2.2
    - jenkspy ==0.1.4
    - pyaml ==17.8.0
    - pyutilsnrw ==0.1.1
    - matplotlib ==1.5.3
    - pandas ==0.20.1
    - coverage ==4.4.1
    - numpy ==1.11.3
    - nose ==1.3.7
  run:
    # python reqs
    - python
    - biopython ==1.68
    - jenkspy ==0.1.4
    - pyaml ==17.8.0
    - pysam ==0.11.2.2
    - pyutilsnrw ==0.1.1
    - matplotlib ==1.5.3
    - pandas ==0.20.1
    - coverage ==4.4.1
    - numpy ==1.11.3
    - nose ==1.3.7
    # sys reqs
    - emboss
    - barrnap ==0.7
    - mafft
    - prank
    - spades ==3.9.0
    - bwa ==0.7.8
    - samtools ==1.4.1
    - bcftools ==1.5

test:
  imports:
    - riboSeed

about:
  home: https://github.com/nickp60/riboSeed
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'riboSeed: assemble across rDNA regions'
  description: "Genome assembly polisher to bridge rDNA gaps"
  dev_url: 'https://github.com/nickp60/riboSeed'

extra:
  recipe-maintainers:
    - nickp60
